# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lematinalproject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


 pod 'SDWebImage'
 pod 'IQKeyboardManager'
 pod 'DialCountries'

  # Pods for Lematinalproject

  target 'LematinalprojectTests' do
    inherit! :search_paths
    # Pods for testing
   
  end

  target 'LematinalprojectUITests' do
    # Pods for testing
  end

end
